import { Cpu, Drama, Zap, BookOpen, Palette, Globe } from "lucide-react";

export const CLUB_CATEGORIES = ["technical", "cultural", "sports", "academic", "arts", "other"];

export const CLUB_CATEGORY_META = {
  technical: {
    Icon: Cpu,
    desc: "Coding, robotics, engineering",
    gradient: "cc-club-gradient-technical",
    color: "cc-club-gradient-technical",
    badge: "cc-club-badge-technical",
    accent: "cc-club-accent-technical",
    heroBg: "cc-club-hero-technical",
    ring: "cc-club-ring-technical",
    tabActive: "cc-club-tab-technical",
  },
  cultural: {
    Icon: Drama,
    desc: "Drama, music, festivals",
    gradient: "cc-club-gradient-cultural",
    color: "cc-club-gradient-cultural",
    badge: "cc-club-badge-cultural",
    accent: "cc-club-accent-cultural",
    heroBg: "cc-club-hero-cultural",
    ring: "cc-club-ring-cultural",
    tabActive: "cc-club-tab-cultural",
  },
  sports: {
    Icon: Zap,
    desc: "Athletics, fitness, competition",
    gradient: "cc-club-gradient-sports",
    color: "cc-club-gradient-sports",
    badge: "cc-club-badge-sports",
    accent: "cc-club-accent-sports",
    heroBg: "cc-club-hero-sports",
    ring: "cc-club-ring-sports",
    tabActive: "cc-club-tab-sports",
  },
  academic: {
    Icon: BookOpen,
    desc: "Research, debate, study groups",
    gradient: "cc-club-gradient-academic",
    color: "cc-club-gradient-academic",
    badge: "cc-club-badge-academic",
    accent: "cc-club-accent-academic",
    heroBg: "cc-club-hero-academic",
    ring: "cc-club-ring-academic",
    tabActive: "cc-club-tab-academic",
  },
  arts: {
    Icon: Palette,
    desc: "Visual arts, design, film",
    gradient: "cc-club-gradient-arts",
    color: "cc-club-gradient-arts",
    badge: "cc-club-badge-arts",
    accent: "cc-club-accent-arts",
    heroBg: "cc-club-hero-arts",
    ring: "cc-club-ring-arts",
    tabActive: "cc-club-tab-arts",
  },
  other: {
    Icon: Globe,
    desc: "Everything else",
    gradient: "cc-club-gradient-other",
    color: "cc-club-gradient-other",
    badge: "cc-club-badge-other",
    accent: "cc-club-accent-other",
    heroBg: "cc-club-hero-other",
    ring: "cc-club-ring-other",
    tabActive: "cc-club-tab-other",
  },
};
